name: CI
on:
  push:
    branches: ['21.x']
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-test:
    name: Angular 21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx ng lint
      - run: npx ng build angular-image-editor
      - run: npx ng test angular-image-editor --watch=false
